### ISSUE TITLE
How to get frequency from phase and amplitude?

### ISSUE THREAD

**Issue by Harrolee** [jmerc77/Fast4ier#1]
Hey! Great work.

Your example prints phase and amplitude:
```
for(int i=0;i<BINS;i++)
{
  Serial.print(vals[i].re());
  Serial.print(F(" + "));
  Serial.print(vals[i].im());
  Serial.println(F("i"));
}
```

How do I calculate frequency from phase and amplitude?

**Comment by jmerc77** [comment]
sort answer: you can't.

long answer: phase and amplitude are with in a bin (after converting them using toPolar(...)), which represents a sliver of the possible frequencies. you get true complex numbers without converting with toPolar(...). the print you described is not in polar form. that is in example 2. because of the range-like nature of a bin, a single sample of FFT is not enough to determine the actual frequency. however, if you overlap 2 samples of FFT by 75%, you can use an algorithm similar to a phase vocoder to get a better idea of the actual frequency by analyzing the change in phase between both samples for each bin.
